### ISSUE TITLE
reactor: remove `wget` dependency

### ISSUE THREAD

**Issue by hanchon** [hanchon/hanchond#51]
We are only using `wget` to download `gaiad`, but we can directly get the binary using `http.Get` from go std lib.

The code that needs to be modified is [here](https://github.com/hanchon/hanchond/blob/main/playground/gaia/get_gaiad.go#L10-L10)

And instead of using `wget` is should download it the same as `soloc`: [here](https://github.com/hanchon/hanchond/blob/main/playground/solidity/download.go#L64-L64)

It "downloads" the file using `http.Get`, then it `io.Copy` the body to a file and lastly it changes the permissions so it can executed.

**Comment by Blackvote** [comment]
Hi. Can i help you with this issue?

**Comment by hanchon** [comment]
Yes @Blackvote , feel free to create a PR
